source 'https://cdn.cocoapods.org'

target 'SFShop' do
  pod 'AFNetworking'
  pod 'OYCountDownManager'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'JSONModel'
  pod 'YYModel'
  pod 'FMDB'
  pod 'MJRefresh', :path => 'Repos/MJRefresh'
  pod 'IQKeyboardManager'
  pod 'JTCalendar', '~> 2.0'
  pod 'JKCategories'
  pod 'VTMagic'
  pod 'SDWebImage'
  pod 'iCarousel'
  pod 'ReactiveObjC'
  pod 'SJVideoPlayer'
end 
